cd tmp/quickstart/jars
docker cp animal-sniffer-annotations-1.17.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp checker-qual-2.5.2.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-beanutils-1.9.3.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-collections-3.2.2.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-collections4-4.2.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-compress-1.18.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-lang3-3.8.1.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-logging-1.2.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp commons-text-1.3.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp connect-utils-0.4.155.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp error_prone_annotations-2.2.0.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp extended-log-format-0.0.1.5.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp failureaccess-1.0.1.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp freemarker-2.3.28.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp guava-27.1-jre.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp j2objc-annotations-1.1.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp jackson-annotations-2.9.0.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp jackson-core-2.9.9.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp jackson-databind-2.9.9.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp javassist-3.21.0-GA.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp jsr305-3.0.2.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp kafka-connect-spooldir-1.0-SNAPSHOT.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp opencsv-4.5.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp reflections-0.9.11.jar kafka-connect-avro:/etc/kafka-connect/jars
docker cp value-2.5.5.jar kafka-connect-avro:/etc/kafka-connect/jars
